name: CI/CD con Tests y GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Instalar dependencias
      run: bun install

    - name: Ejecutar tests
      run: bun test.js

    - name: Notificar a Slack si fallan los tests
      if: failure()
      env:
        COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{
          \"text\": \"❌ Fallaron los tests en *${{ github.repository }}*\n
          • Autor: ${{ github.actor }}\n
          • Mensaje del commit: $(git log -1 --pretty=%B)\n
          • Enlace al commit: ${COMMIT_URL}\"
        }" \
        ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Instalar dependencias
      run: bun install

    - name: Ejecutar build con Vite
      run: bun run build

    - name: Configurar Pages
      uses: actions/configure-pages@v5

    - name: Subir artefacto de GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist

    - name: Desplegar a GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Notificar a Slack si el despliegue fue exitoso
      if: success()
      env:
        COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{
          \"text\": \"✅ *Despliegue exitoso con build de Vite* en *${{ github.repository }}* 🚀\n
          • Autor: ${{ github.actor }}\n
          • Mensaje del commit: $(git log -1 --pretty=%B)\n
          • Enlace al commit: ${COMMIT_URL}\"
        }" \
        ${{ secrets.SLACK_WEBHOOK_URL }}
