name: CI/CD con Tests y GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar tests
      run: node test.js

    - name: Notificar a Slack si fallan los tests
      if: failure()
      env:
        COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{
          \"text\": \"❌ Fallaron los tests en *${{ github.repository }}*\n
          • Autor: ${{ github.actor }}\n
          • Mensaje del commit: $(git log -1 --pretty=%B)\n
          • Enlace al commit: ${COMMIT_URL}\"
        }" \
        ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    # Copiar index.js al directorio dist/ para uso en el navegador
    - name: Copiar index.js a dist/
      run: cp index.js dist/

    - name: Configurar Pages
      uses: actions/configure-pages@v5

    - name: Subir artefacto de GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist

    - name: Desplegar a GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Notificar a Slack si el despliegue fue exitoso
      if: success()
      env:
        COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{
          \"text\": \"✅ *Despliegue exitoso en GitHub Pages* para el repositorio *${{ github.repository }}* 🚀\n
          • Autor: ${{ github.actor }}\n
          • Mensaje del commit: $(git log -1 --pretty=%B)\n
          • Enlace al commit: ${COMMIT_URL}\"
        }" \
        ${{ secrets.SLACK_WEBHOOK_URL }}
