name: CI/CD de Node.js + HTML con GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar tests
      run: node test.js

    - name: Notificar a Slack si fallan los tests
      if: failure()
      env:
        COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{
          \"text\": \"❌ Fallaron los tests en *${{ github.repository }}*\n
          • Autor: ${{ github.actor }}\n
          • Mensaje del commit: $(git log -1 --pretty=%B)\n
          • Enlace al commit: ${COMMIT_URL}\"
        }" \
        ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
